apiVersion: v1
kind: Service
metadata:
  name: brain-task-service
  annotations:
    # Optional: enables TCP/HTTP health check on "/" path
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/"
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"
spec:
  type: LoadBalancer
  selector:
    app: brain-task          # must match deployment pod labels exactly
  ports:
    - protocol: TCP
      port: 80               # LB port
      targetPort: 80         # Pod container port
